survey_folder_path: ../../example/demo_generator
excel_file_path: ../../example/demo_generator/references/Household_Travel_Generate_Survey.xlsx

enabled_scripts:
    generate_excel: false
    generate_section_configs: true
    generate_sections: true
    generate_widgets_configs: true
    generate_widgets: true
    generate_conditionals: true
    generate_choices: true
    generate_input_range: true
    generate_labels: true
    generate_UI_tests: true
    generate_questionnaire_list: true
    generate_questionnaire_dictionary: true
